import { Hono } from "hono";
import type { AppEnv } from "../types";
import { agentRoutes } from "./agent";
import { attachmentRoutes } from "./attachments";
import { deliverabilityRoutes } from "./deliverability";
import { domainRoutes } from "./domains";
import { draftRoutes } from "./drafts";
import { inboxRoutes } from "./inboxes";
import { keyRoutes } from "./keys";
import { messageRoutes } from "./messages";
import { orgRoutes } from "./orgs";
import { suppressionRoutes } from "./suppressions";
import { threadRoutes } from "./threads";
import { usageRoutes } from "./usage";
import { webhookRoutes } from "./webhooks";

export const routes = new Hono<AppEnv>();

routes.route("/", agentRoutes);
routes.route("/", keyRoutes);
routes.route("/", orgRoutes);
routes.route("/", inboxRoutes);
routes.route("/", threadRoutes);
routes.route("/", messageRoutes);
routes.route("/", draftRoutes);
routes.route("/", attachmentRoutes);
routes.route("/", domainRoutes);
routes.route("/", webhookRoutes);
routes.route("/", suppressionRoutes);
routes.route("/", usageRoutes);
routes.route("/", deliverabilityRoutes);
